builders:
  logger_generator:
    import: "package:lt_generator/logger_generator.dart"
    builder_factories: ["loggerBuilder"]
    build_extensions: {".dart" : [".logger_generator.g.part"]}
    auto_apply: dependents
    build_to: cache

  json_deserialization_generator:
      import: "package:lt_generator/ltdeserialization_generator.dart"
      builder_factories: ["jsonDeserializationBuilder"]
      build_extensions: {".dart" : [".json_model_generator.g.part"]}
      auto_apply: dependents
      build_to: cache

    
  