---
include: 
  - ../../fastlane/project/settings.yml

name: Common

settings:
  groups:
    - BaseProjectSetting

targets:
  Common:
    type: framework
    platform: iOS
    sources:
      - Source
    settings:
      groups:
        - BaseTargetSetting
schemes:
  Common:
    templates:
      - DefaultSchemeTemplate
    templateAttributes:
      testTargetName: Common