---
include: 
  - ../../fastlane/project/settings.yml

name: Network

settings:
  groups:
    - BaseProjectSetting

targets:
  LTNetwork:
    type: framework
    platform: iOS
    sources:
      - Source
    settings:
      groups:
        - BaseTargetSetting
    info:
      path: Source/Info.plist
shemes:
  LTNetwork:
    templates:
      - DefaultSchemeTemplate
    templateArributes:
      testTargetName: LTNetwork