---
include:
  - ../../fastlane/project/settings.yml

name: LTApp

configs:
  Debug: debug
  Release: release
  Release-Debug: release

options:
  defaultConfig: Debug

settings:
  groups:
    - BaseProjectSetting
  configs:
    Release-Debug:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      OTHER_SWIFT_FLAGS: "-DDEBUG"

packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    from: "8.6.2"
  SVGKit:
    url: https://github.com/SVGKit/SVGKit
    from: "3.0.0"

targets:
  LTApp:
    type: application
    platform: iOS
    sources:
      - LTApp/Source
      - LTApp/Resource/Assets.xcassets
      - LTApp/Resource/LaunchScreen.storyboard
      - LTApp/Resource/Info.plist
    settings:
      groups:
        - BaseTargetSetting
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.little.things
        PRODUCT_NAME: LTApp
        SWIFT_VERSION: "6.0"
        IPHONE_DEPLOYMENT_TARGET: "18.0"
        INFOPLIST_FILE: LTApp/Resource/Info.plist
        CODE_SIGN_ENTITLEMENTS: LTApp/Resource/LTApp.entitlements
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: R7S4TKW9JF
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: "NO"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: "YES"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "YES"
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
          PROVISIONING_PROFILE_SPECIFIER: littile_thins_ios_dev
        Release:
          CODE_SIGN_IDENTITY: "iPhone Distribution: Shanghai Weishu Weixiang Network Technology Co., Ltd. (R7S4TKW9JF)"
          PROVISIONING_PROFILE_SPECIFIER: littile_things_distribute_profile
        Release-Debug:
          CODE_SIGN_IDENTITY: "iPhone Distribution: Shanghai Weishu Weixiang Network Technology Co., Ltd. (R7S4TKW9JF)"
          PROVISIONING_PROFILE_SPECIFIER: littile_things_distribute_profile
    dependencies:
      - package: Kingfisher
      - package: SVGKit
        product: SVGKit
      - package: SVGKit
        product: SVGKitSwift
      - framework: LTNetwork.framework
        implicit: true
      - framework: Persistence.framework
        implicit: true
      - framework: UIComponent.framework
        implicit: true
      - framework: LTCommon.framework
        implicit: true

  LTAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - LTApp/Tests
    dependencies:
      - target: LTApp
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: com.LTAppTests

schemes:
  LTApp:
    build:
      targets:
        LTApp: all
    test:
      targets:
        - name: LTAppTests
          randomExecutionOrder: false
      gatherCoverageData: true
