name: LTApp
options:
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.44.1"
  bundleIdPrefix: com.little.things
  deploymentTarget: 
    iOS: 18.0
    defaultConfig: Debug
 

targets:
 LTApp:
  type: application
  supportedDestinations: [iOS]
  deploymentTarget:
    iOS: 9.0
  sources:
    - path: LTApp/Source
    - path: LTApp/Resource
  dependencies:
    - framework: LTNetwork.framework
      implicit: true
    - framework: Persistence.framework
      implicit: true
    - framework: UIComponent.framework
      implicit: true
  settings:
    base:
      PRODUCT_NAME: LTApp
      SWIFT_VERSION: 6.0
      IPHONE_DEPLOYMENT_TARGET: 18.0
      DEVELOPMENT_TEAM: R7S4TKW9JF
      PRODUCT_BUNDLE_IDENTIFIER: com.little.things
      CODE_SIGN_STYLE: Manual
      CODE_SIGN_ENTITLEMENTS: LTApp/Resource/LTApp.entitlements
      INFOPLIST_FILE: LTApp/Resource/Info.plist
    configs:
      debug:
        CODE_SIGN_IDENTITY: "iPhone Developer: Tianwei LIU (MU9J2K22B8)"
        PROVISIONING_PROFILE_SPECIFIER: little.things.dev.profile 
      release:
        CODE_SIGN_IDENTITY: iPhone Distribution
        PROVISIONING_PROFILE_SPECIFIER: little.things.adhoc.profile