-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgAJKz3Zd6ZGnxnlFG
NVXyKSvoSbS91p5DG5eAg0togIqgCgYIKoZIzj0DAQehRANCAAThf6PXrXqLDjfD
I0v/yumzGSygcfdxZoz2e0gD3Yfz7hpXAaibqRrGf4ktyXeHVPCn5Z+EtrVJs0Xb
ZMnjjOul
-----END PRIVATE KEY-----