# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end


  lane :internal_test do
    build_number_file =".buldversion"
    current_build = File.exist?(build_number_file) ? File.read(build_number_file).to_i : 1

    increment_build_number(
      build_number: current_build,
      xcodeproj: "LTApp.xcodeproj",
      skip_info_plist: true
    )
    
    build_app(
      project: 'LTApp.xcodeproj',
      scheme: 'LTApp',
      export_method: "ad-hoc",
      export_options: {
        provisioningProfiles: {
          "com.little.things" => "little.things.adhoc.profile"
        }
      }
    )

    api_key = app_store_connect_api_key(
      key_id: "XK2Z7K45R8",
      issuer_id: "c56185f7-9f75-47bc-b863-207149642302",
      key_filepath: "fastlane/AuthKey_XK2Z7K45R8.p8",
    )
    upload_to_testflight(
      api_key: api_key,
      # username: "vsvx.sh.co@outlook.com",
      app_identifier: "com.little.things",
      skip_waiting_for_build_processing: false,
      notify_external_testers: false
    )

    new_build = current_build + 1
    File.write(build_number_file, new_build)
  end

end
