---
include: 
  - ../../fastlane/project/settings.yml

name: UIComponent

settings:
  groups:
    - BaseProjectSetting


packages:
  Lottie:
    url: https://github.com/airbnb/lottie-ios
    exactVersion: 4.5.1

targets:
  UIComponent:
    type: framework
    platform: iOS
    sources:
      - Source
    settings:
      groups:
        - BaseTargetSetting
    dependencies:
    - package: Lottie
      product: Lottie
schemes:
  UIComponent:
    templates:
      - DefaultSchemeTemplate
    templateAttributes:
      testTargetName: UIComponent
