#!/bin/bash

# =============================================================================
# 版权声明批量更新脚本
# 用于更新项目中所有代码文件的版权声明为统一格式
# 
# 使用方法:
#   ./update_copyright.sh                    # 运行脚本
#   ./update_copyright.sh --dry-run         # 预览模式
#   ./update_copyright.sh --author "Custom" # 指定作者
# =============================================================================

# ==================== 配置区域 ====================
AUTHOR="lieon"
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DRY_RUN=false
VERBOSE=false
BACKUP=true

# 目标文件扩展名
FILE_EXTENSIONS="swift h m"

# 排除的目录
EXCLUDE_DIRS="Pods .build DerivedData Carthage vendor node_modules .git .xcodeproj .xcworkspace .swiftpm"

# ==================== 颜色定义 ====================
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# ==================== 帮助信息 ====================
show_help() {
    cat << EOF
用法: $(basename "$0") [选项]

批量更新项目中所有代码文件的版权声明为统一格式。

选项:
    -a, --author <名称>     指定作者名称 (默认: lieon)
    -d, --dry-run          预览模式，不实际修改文件
    -v, --verbose          显示详细信息
    -b, --backup           备份原文件 (*.bak) (默认开启)
    -h, --help             显示帮助信息

版权声明格式:
    //
    //  Created by {author} on {year}/{month}/{day}.
    //  This code is protected by intellectual property rights.
    //

示例:
    $(basename "$0")                    # 运行脚本
    $(basename "$0") --dry-run          # 预览模式
    $(basename "$0") --author "Custom"  # 指定作者
EOF
}

# ==================== 解析命令行参数 ====================
while [[ $# -gt 0 ]]; do
    case $1 in
        -a|--author)
            AUTHOR="$2"
            shift 2
            ;;
        -d|--dry-run)
            DRY_RUN=true
            shift
            ;;
        -v|--verbose)
            VERBOSE=true
            shift
            ;;
        -b|--backup)
            BACKUP=true
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            echo -e "${RED}未知选项: $1${NC}"
            show_help
            exit 1
            ;;
    esac
done

# ==================== 日志函数 ====================
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_verbose() {
    if $VERBOSE; then
        echo -e "${CYAN}[DEBUG]${NC} $1"
    fi
}

# ==================== 版权声明模板 ====================
generate_copyright_header() {
    local current_date
    current_date=$(date "+%Y/%m/%d")
    cat <<EOF
//
//  Created by ${AUTHOR} on ${current_date}.
//  This code is protected by intellectual property rights.
//
EOF
}

# ==================== 扫描项目文件 ====================
scan_files() {
    local count=0
    
    # 使用 find 命令查找文件
    while IFS= read -r file; do
        # 过滤掉排除目录中的文件
        local should_exclude=false
        for dir in $EXCLUDE_DIRS; do
            if [[ "$file" == *"/$dir/"* ]]; then
                should_exclude=true
                break
            fi
        done
        
        if ! $should_exclude; then
            echo "$file"
            ((count++))
        fi
    done < <(find "$PROJECT_ROOT" -type f \( -name "*.swift" -o -name "*.h" -o -name "*.m" \) 2>/dev/null)
}

# ==================== 检测文件是否有版权声明 ====================
has_copyright() {
    local file="$1"
    
    # 检测常见的版权声明模式
    grep -qiE '(Created by|This code is protected|Copyright)' "$file" 2>/dev/null
    return $?
}

# ==================== 清理版权声明 ====================
clean_copyright() {
    local file="$1"
    
    # 读取文件内容
    local content
    content=$(cat "$file")
    
    # 移除版权声明块（从开头的 // 行到第一个非 // 行）
    local cleaned=""
    local in_copyright=false
    local first_code_line=false
    
    while IFS= read -r line; do
        # 检查是否是版权声明行
        if [[ "$line" =~ ^//.*(Created by|This code is protected|intellectual property|Copyright|Generated by|Module|Target) ]]; then
            in_copyright=true
            continue
        elif [[ "$line" =~ ^//[[:space:]]*$ ]] && $in_copyright; then
            # 版权声明后的空行
            continue
        elif [[ "$line" =~ ^// ]]; then
            # 其他以 // 开头的行（如 // filename.swift）
            continue
        else
            # 这是实际的代码行
            if ! $first_code_line; then
                cleaned="$line"
                first_code_line=true
            else
                cleaned="$cleaned"$'\n'"$line"
            fi
            in_copyright=false
        fi
    done <<< "$content"
    
    echo "$cleaned"
}

# ==================== 替换版权声明 ====================
replace_copyright() {
    local file="$1"
    local new_header
    local current_date
    
    current_date=$(date "+%Y/%m/%d")
    new_header="//
//  Created by ${AUTHOR} on ${current_date}.
//  This code is protected by intellectual property rights.
//"
    
    if $BACKUP && ! $DRY_RUN; then
        cp "$file" "${file}.bak"
    fi
    
    # 清理现有版权声明并添加新的
    local cleaned
    cleaned=$(clean_copyright "$file")
    
    if ! $DRY_RUN; then
        echo -e "${new_header}\n${cleaned}" > "$file"
    fi
}

# ==================== 添加版权声明 ====================
add_copyright() {
    local file="$1"
    local current_date
    local new_header
    
    current_date=$(date "+%Y/%m/%d")
    new_header="//
//  Created by ${AUTHOR} on ${current_date}.
//  This code is protected by intellectual property rights.
//"
    
    if $BACKUP && ! $DRY_RUN; then
        cp "$file" "${file}.bak"
    fi
    
    if ! $DRY_RUN; then
        # 在文件开头添加版权声明
        echo -e "${new_header}\n$(cat "$file")" > "$file"
    fi
}

# ==================== 处理单个文件 ====================
process_file() {
    local file="$1"
    local relative_path="${file#$PROJECT_ROOT/}"
    
    if has_copyright "$file"; then
        log_verbose "替换版权声明: $relative_path"
        replace_copyright "$file"
        echo "REPLACED:$relative_path"
    else
        log_verbose "添加版权声明: $relative_path"
        add_copyright "$file"
        echo "ADDED:$relative_path"
    fi
}

# ==================== 统计处理结果 ====================
generate_report() {
    local total=$1
    local replaced=$2
    local added=$3
    local skipped=$4
    
    echo ""
    echo "=============================================="
    echo -e "${BLUE}版权声明更新报告${NC}"
    echo "=============================================="
    echo -e "作者: ${AUTHOR}"
    echo -e "日期: $(date '+%Y-%m-%d %H:%M:%S')"
    echo ""
    echo "统计:"
    echo -e "  ${GREEN}已替换:${NC}  $replaced"
    echo -e "  ${GREEN}已添加:${NC}  $added"
    if $BACKUP && ! $DRY_RUN; then
        echo -e "  ${BLUE}备份文件:${NC}  已创建 .bak 文件"
    fi
    echo "  ----------------------------------------"
    echo -e "  ${BLUE}总计:${NC}      $total"
    echo "=============================================="
    
    if $DRY_RUN; then
        echo ""
        echo -e "${YELLOW}[预览模式] 以上为预计变更，未实际修改文件${NC}"
        echo ""
        echo "去掉 --dry-run 参数以执行实际修改"
    fi
}

# ==================== 主程序 ====================
main() {
    echo ""
    echo "=============================================="
    echo -e "${BLUE}版权声明批量更新脚本${NC}"
    echo "=============================================="
    echo ""
    
    if $DRY_RUN; then
        log_warning "运行于预览模式，不会实际修改文件"
        echo ""
    fi
    
    log_info "项目根目录: $PROJECT_ROOT"
    log_info "作者: $AUTHOR"
    log_info "开始扫描代码文件..."
    
    # 扫描文件
    local files
    files=$(scan_files)
    
    # 转换为数组 (兼容 macOS)
    local file_array=()
    while IFS= read -r line; do
        [[ -n "$line" ]] && file_array+=("$line")
    done <<< "$files"
    local total=${#file_array[@]}
    
    if [[ $total -eq 0 ]]; then
        log_error "未找到任何代码文件"
        exit 1
    fi
    
    log_success "找到 $total 个代码文件"
    echo ""
    log_info "开始处理..."
    
    # 处理统计
    local replaced=0
    local added=0
    
    # 处理每个文件
    for file in "${file_array[@]}"; do
        if [[ -z "$file" || ! -f "$file" ]]; then
            continue
        fi
        
        # 检查文件是否可读
        if [[ ! -r "$file" ]]; then
            continue
        fi
        
        # 处理文件
        local result
        result=$(process_file "$file" 2>&1)
        
        if [[ "$result" == REPLACED:* ]]; then
            ((replaced++))
        elif [[ "$result" == ADDED:* ]]; then
            ((added++))
        fi
    done
    
    # 生成报告
    generate_report "$total" "$replaced" "$added" "0"
    
    echo ""
    log_success "完成!"
}

# 执行主程序
main
