configs:
  Debug: debug
  Release: release
  Release-Debug: release

settings:
  configs:
    Release-Debug:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      OTHER_SWIFT_FLAGS: "-DDEBUG"

options:
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.44.1"
  bundleIdPrefix: com.little.things
  deploymentTarget: 
    iOS: "18.0"
    defaultConfig: Debug

settingGroups:
  BaseProjectSetting:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: true
  BaseTargetSetting:
    base:
      INFOPLIST_FILE: Source/Info.plist
      SWIFT_VERSION: 6.0
      IPHONE_DEPLOYMENT_TARGET: 18.0
  BaseTestTargetSetting:
    base:
      GENERATE_INFOPLIST_FILE: true
      IPHONEOS_DEPLOYMENT_TARGET: 18.0
      ENABLE_USER_SCRIPT_SANDBOXING: false

schemeTemplates:
  DefaultSchemeTemplate:
    templates:
      - DefaultScheme
    build:
      targets:
        ${scheme_name}: all
  
  DefaultScheme:
    test:
      targets:
        - name: "${testTargetName}"
          randomExecutionOrder: false
      gatherCoverageData: true
      language: en
      region: US
      coverageTargets:
        - name: "${testTargetName}"